SET( ${TARGETLIB}_SOURCES
pkg-selector-help.cc
YGPackageSelector.cc
YGPackageSelectorPluginImpl.cc
ygtkpkgdetailview.cc
ygtkpkgfilterview.cc
ygtkpkghistorydialog.cc
ygtkpkglanguageview.cc
ygtkpkglistview.cc
ygtkpkgmenubar.cc
ygtkpkgpatternview.cc
ygtkpkgproductdialog.cc
ygtkpkgquerycombo.cc
ygtkpkgrpmgroupsview.cc
ygtkpkgsearchentry.cc
ygtkpkgstatusbar.cc
ygtkpkgundolist.cc
ygtkpkgvestigialdialog.cc
ygtktreemodel.cc
yzypptags.cc
yzyppwrapper.cc
ygtkcellrendererbutton.c 
ygtkcellrenderersidebutton.c
ygtkcellrenderertext.c
)

SET( ${TARGETLIB}_HEADERS
config.h.cmake
YGPackageSelector.h
YGPackageSelectorPluginImpl.h
ygtkcellrendererbutton.h
ygtkcellrenderersidebutton.h
ygtkcellrenderertext.h
ygtkpkgdetailview.h
ygtkpkgfilterview.h
ygtkpkghistorydialog.h
ygtkpkglanguageview.h
ygtkpkglistview.h
ygtkpkgmenubar.h
ygtkpkgpatternview.h
ygtkpkgproductdialog.h
ygtkpkgquerycombo.h
ygtkpkgquerywidget.h
ygtkpkgrpmgroupsview.h
ygtkpkgsearchentry.h
ygtkpkgstatusbar.h
ygtkpkgundolist.h
ygtkpkgvestigialdialog.h
ygtktreemodel.h
yzypptags.h
yzyppwrapper.h
)
